version: "0.2"
ignorePaths:
  - mvnw.cmd
  - mvnw
dictionaryDefinitions: []
dictionaries: []
words:
  - databind
  - endlocal
  - ERRORLEVEL
  - flexjson
  - setlocal
  - shak
  - Stratford
  - WillShak
  - zipcodes
ignoreWords: []
import: []
