CREATE TABLE IF NOT EXISTS person (
    id              INT         GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    first_name      VARCHAR(50) NOT NULL,
    last_name       VARCHAR(50) NOT NULL
);