# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Build Test

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      id: setup-java-17
      uses: actions/setup-java@v4
      with:                
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        mvn-toolchain-vendor: Eclipse Temurin
        java-version: |
          8
          11
          17
        mvn-toolchain-id: |
          8
          11
          17

    # - uses: cactuslab/maven-toolchains-xml-action@v1
    #   with:
    #     toolchains: |
    #       [
    #         {"jdkVersion": "17", "jdkHome": "${{ env.JAVA_HOME }}"}
    #       ]

    - name: Build with Maven (struts2-junit5-user-custom-plugin install)
      run: mvn -B install --file pom.xml

    - name: Build with Maven (Projects)
      run: mvn -B install --file struts2-study-parent/pom.xml

#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
